image: docker:git

services:
  - docker:dind

before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
  - docker login -u gbraad -p $DOCKER_PASSWORD

build:
  script:
    - docker build -t registry.gitlab.com/gbraad/hostenter:latest . 
    - docker push registry.gitlab.com/gbraad/hostenter:latest
    - docker tag registry.gitlab.com/gbraad/hostenter gbraad/hostenter:latest
    - docker push gbraad/hostenter:latest
  only:
    - master
  when: manual
